In [8]:
import pandas as pd

# Load the Titanic dataset
# Replace 'titanic.csv' with the path to your dataset file
titanic = pd.read_csv('/content/drive/MyDrive/AI dataset/Datasets-20241202T063912Z-001/Datasets/Titanic-Dataset.csv')

# Step 1: Calculate the total fare paid across all passengers
total_fare = titanic['Fare'].sum()

# Step 2: Subset data by passenger class and calculate their total fares
first_class_total = titanic[titanic['Pclass'] == 1]['Fare'].sum()
second_class_total = titanic[titanic['Pclass'] == 2]['Fare'].sum()
third_class_total = titanic[titanic['Pclass'] == 3]['Fare'].sum()

# Step 3: Combine the fare totals into a list
fare_totals = [first_class_total, second_class_total, third_class_total]

# Step 4: Divide the totals by the overall total fare to get proportions
proportions = [fare / total_fare for fare in fare_totals]

# Print the results
print(f"Total Fare Paid: ${total_fare}")
print(f"Total fare from First Class: ${first_class_total}")
print(f"Total fare from Second Class: ${second_class_total}")
print(f"Total fare from Third Class: ${third_class_total}")
print("Proportion of fare revenue by class:")
print(f"First Class: {proportions[0] * 100:.2f}%")
print(f"Second Class: {proportions[1] * 100:.2f}%")
print(f"Third Class: {proportions[2] * 100:.2f}%")

Total Fare Paid: $28693.9493
Total fare from First Class: $18177.4125
Total fare from Second Class: $3801.8417
Total fare from Third Class: $6714.6951
Proportion of fare revenue by class:
First Class: 63.35%
Second Class: 13.25%
Third Class: 23.40%

In [9]:
import pandas as pd

# Load the Titanic dataset
# Replace 'titanic.csv' with the path to your dataset file
titanic = pd.read_csv('/content/drive/MyDrive/AI dataset/Datasets-20241202T063912Z-001/Datasets/Titanic-Dataset.csv')

# Step 1: Create a new column 'AgeGroup' to categorize passengers
def categorize_age(age):
    if age < 18:
        return 'child'
    elif 18 <= age < 65:
        return 'adult'
    else:
        return 'senior'

# Apply the function to create the age group column
titanic['AgeGroup'] = titanic['Age'].apply(lambda x: categorize_age(x) if not pd.isnull(x) else 'unknown')

# Step 2: Calculate the total number of passengers
total_passengers = len(titanic)

# Step 3: Count the number of passengers in each age group
age_group_counts = titanic['AgeGroup'].value_counts(normalize=True)  # Normalize gives proportions

# Step 4: Convert proportions to percentages
age_group_percent = age_group_counts * 100

# Print the results
print(f"Total number of passengers on the Titanic: {total_passengers}")
print(f"Proportion of passengers by age group:")
print(f"Child: {age_group_percent.get('child', 0):.2f}%")
print(f"Adult: {age_group_percent.get('adult', 0):.2f}%")
print(f"Senior: {age_group_percent.get('senior', 0):.2f}%")

Total number of passengers on the Titanic: 891
Proportion of passengers by age group:
Child: 12.68%
Adult: 66.22%
Senior: 1.23%